name: Serverless Devs Project CI/CD

on:
  release:
    types: [created]

jobs:
  serverless-devs-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm install -g @serverless-devs/s
      - run: s cli registry login --token ${{secrets.Token}} 
      - run: s cli registry publish